# vim: set tabstop=2 shiftwidth=2 expandtab ft=yaml
- project:
    name: leifmadsen/dummy-commits
    check:
      jobs:
          - hello-world

- job:
    name: hello-world
    parent: base
    run: playbooks/run.yaml
    timeout: 900
